# Generated by Django 4.2.22 on 2025-06-12 02:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seats', '0002_seat_is_confirmed_alter_seat_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='location',
            name='icon',
            field=models.CharField(default='fa-building-columns', help_text="Font Awesome 6 solid icon class, e.g., 'fa-users', 'fa-desktop', etc.", max_length=50),
        ),
        migrations.AddField(
            model_name='seat',
            name='reserved_at',
            field=models.DateTimeField(blank=True, help_text='Timestamp of when the seat was booked or confirmed.', null=True),
        ),
    ]
