# Generated by Django 4.2.22 on 2025-06-17 04:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('seats', '0003_location_icon_seat_reserved_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='location',
            name='icon',
        ),
        migrations.RemoveField(
            model_name='seat',
            name='reserved_at',
        ),
    ]
